name: Auto Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-server
  cancel-in-progress: true

on:
  push:
    branches: [master, 1.23.X, 3.0.0]
  pull_request:
permissions: {}

jobs:
  auto-test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest, ubuntu-22.04-arm]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node: [20, 24]
        # Also test non-LTS, but only on Ubuntu.
        include:
          - os: ubuntu-22.04
            node: 25

    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }

      - name: Cache/Restore node_modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm clean-install --no-fund

      - name: Rebuild native modules for ARM64
        if: matrix.os == 'ubuntu-22.04-arm'
        run: npm rebuild @louislam/sqlite3

      - run: npm run build
      - run: npm run test-backend
        env:
          HEADLESS_TEST: 1
          JUST_FOR_TEST: ${{ secrets.JUST_FOR_TEST }}

  # As a lot of dev dependencies are not supported on ARMv7, we have to test it separately and just test if `npm ci --production` works
  armv7-simple-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Test on ARMv7 using Docker with QEMU
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v $PWD:/workspace \
            -w /workspace \
            arm32v7/node:${{ matrix.node }} \
            npm clean-install --no-fund --production

  check-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }

      - name: Cache/Restore node_modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 20
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 20
      - run: npm clean-install --no-fund
      - run: npm run lint:prod

  e2e-test:
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
    env:
      PLAYWRIGHT_VERSION: ~1.39.0
    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { persist-credentials: false }

      - name: Cache/Restore node_modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
      - run: npm clean-install --no-fund

      - name: Rebuild native modules for ARM64
        run: npm rebuild @louislam/sqlite3

      - name: Install Playwright ${{ env.PLAYWRIGHT_VERSION }}
        run: npx playwright@${{ env.PLAYWRIGHT_VERSION }} install

      - run: npm run build
      - run: npm run test-e2e
